services:
  chess:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
      command: /bin/bash -c "docker build --no-cache ."
    ports: 
      - "8386:5000"
    volumes:
      - .:/app
volumes:
  data:
